"""Local-grid (feet) ↔ WGS84 conversion for the Bear Cub Murray drill data.

The Murray subset uses a non-cardinal local survey grid in feet established
by Hammon Consolidated Gold Fields ca. 1925. The local-grid axes are NOT
true east/north — they're tilted relative to compass directions, which is
why the dh-map drill-hole markers appear in a rotated layout vs. north-up
imagery.

The local-grid → WGS84 transform was derived by composing two affines:

1. **local-grid feet → dh-map pixels** — fit on 23 of 24 holes (hole 6964
   excluded as an OCR-confidence outlier in original log transcription),
   mean residual 5.2 px (~ 10 ft) on the 8x dh-map render. Cartographer
   placed each drill-hole marker accurately relative to its log coordinates.
2. **dh-map pixels → WGS84** — fit on 4 user-clicked corner positions paired
   with GPS-anchored corner WGS84 (anchored on the surviving BLM 2014 brass
   monument at Bear Cub's Corner 4 / SW, marked "BC S1178 C4", and the 2014
   McClintock re-survey's True NW Corner). Mean residual ~80 ft per corner —
   this is the cartographer's drawing imprecision in the red parallelogram
   outline (the cartographer drew the corner outline less precisely than
   the drill-hole markers).

Net absolute accuracy on each hole's WGS84 is ~80 ft (limited by the
cartographer's parallelogram, not by the hole markers).

See `data/raw/bear_cub/SOURCE.md` for full provenance and
`data/raw/bear_cub/dhmap_to_wgs84.json` for the affine values.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np


_FIT_PATH = (
    Path(__file__).resolve().parents[3]
    / "data"
    / "raw"
    / "bear_cub"
    / "dhmap_to_wgs84.json"
)


@dataclass(frozen=True)
class GeorefTransform:
    """Affine transforms for local-grid ↔ dh-map-pixel ↔ WGS84."""

    A_local_to_pixel: np.ndarray  # (3, 2)  [e_ft, n_ft, 1] @ A → (px, py)
    A_pixel_to_wgs84: np.ndarray  # (3, 2)  [px, py, 1] @ A → (lat, lon)
    A_local_to_wgs84: np.ndarray  # (3, 2)  [e_ft, n_ft, 1] @ A → (lat, lon)


def load_transform(fit_path: Path = _FIT_PATH) -> GeorefTransform:
    """Load the composed affine transforms from disk.

    Source of truth is `data/raw/bear_cub/dhmap_to_wgs84.json`, which is
    regenerated by the local-grid-to-WGS84 fitting script when corners or
    hole positions change.
    """
    payload = json.loads(fit_path.read_text())
    return GeorefTransform(
        A_local_to_pixel=np.array(payload["A_local_to_pixel_15x"]),
        A_pixel_to_wgs84=np.array(payload["A_pixel_to_wgs84"]),
        A_local_to_wgs84=np.array(payload["A_local_to_wgs84_combined"]),
    )


def local_to_wgs84(
    e_local_ft: float, n_local_ft: float, transform: GeorefTransform | None = None
) -> tuple[float, float]:
    """Project local-grid feet → WGS84 lat/lon."""
    if transform is None:
        transform = load_transform()
    lat, lon = np.array([e_local_ft, n_local_ft, 1.0]) @ transform.A_local_to_wgs84
    return float(lat), float(lon)


def local_to_pixel(
    e_local_ft: float, n_local_ft: float, transform: GeorefTransform | None = None
) -> tuple[float, float]:
    """Project local-grid feet → dh-map pixel coordinates (1.5x render scale)."""
    if transform is None:
        transform = load_transform()
    px, py = np.array([e_local_ft, n_local_ft, 1.0]) @ transform.A_local_to_pixel
    return float(px), float(py)


# Bear Cub MS 1178 corners — GPS-anchored coordinates.
#
# **Anchor**: BC S1178 C4 brass monument at Corner 4 (SW / "Most southerly"),
# shared with claims MS 1160, MS 1296, and MS 1250. Photographed July 2024
# (`data/raw/bear_cub/misc/IMG_0073.jpg`). The other three corner monuments
# were removed by Dry Gulch mining operations; replacement flags are
# 9-30 ft displaced from true positions.
#
# **TL/Corner 1**: 2014 McClintock re-survey "True NW Corner" — the original
# monument is inside a dredge pond; a witness monument was set 70 ft offset
# but the True coords are what we use here for cartographic alignment.
#
# **TR/Corner 2** and **BR/Corner 3**: computed from the surviving BL anchor
# via the patent's course descriptions (Course 1: N 65°43' E, 622.3 ft;
# Course 2: S 62° E, 1033.5 ft). Closure error around all 4 sides: 8 ft.
#
# Image-orientation labels (TL/TR/BR/BL) follow the dh-map's drawn
# orientation, which is rotated ~90° CCW from north-up. So:
#   image-TL = real-world Most-Westerly  (Corner 1, NW per patent)
#   image-TR = real-world Most-Northerly (Corner 2, NE per patent)
#   image-BR = real-world Most-Easterly  (Corner 3, SE per patent)
#   image-BL = real-world Most-Southerly (Corner 4, SW per patent)
MS_1178_CORNERS = {
    "TL": (64.531854, -165.341649),  # Corner 1 / NW — 2014 survey True NW
    "TR": (64.532556, -165.338029),  # Corner 2 / NE — patent Course 1 from TL
    "BR": (64.531226, -165.332208),  # Corner 3 / SE — patent Course 2 from TR
    "BL": (64.530167, -165.335444),  # Corner 4 / SW — BC S1178 C4 brass monument
}

# Patent course distances (feet) and bearings, for reference.
PATENT_COURSES = (
    ("TL→TR", "N 65°43' E",  622.3),
    ("TR→BR", "S 62° E",     1033.5),
    ("BR→BL", "S 52°18' W",  637.0),
    ("BL→TL", "N 57°36' W",  1155.8),
)
PATENT_AREA_ACRES = 13.786
