"""Print Bear Cub review-checklist issues to stdout.

Reads `data/raw/bear_cub/review_checklist.json` (auto-generated by
`tools/bear_cub_generate_checklist.py`).

Usage:
    uv run python tools/bear_cub_list_review_issues.py              # OPEN items only
    uv run python tools/bear_cub_list_review_issues.py --all        # every item incl. resolved
    uv run python tools/bear_cub_list_review_issues.py --hole "L2 H4"  # one hole
    uv run python tools/bear_cub_list_review_issues.py --status open --status fixed  # filter
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CHECKLIST_FILE = REPO / "data" / "raw" / "bear_cub" / "review_checklist.json"

STATUS_BADGES = {
    "open":         "[open]        ",
    "not_an_issue": "[not_an_issue]",
    "fixed":        "[fixed]       ",
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--all", action="store_true",
                        help="Show every item regardless of status (default: open only)")
    parser.add_argument("--hole", type=str, default=None,
                        help="Filter to one hole (e.g. 'L2 H4')")
    parser.add_argument("--status", action="append", default=None,
                        choices=["open", "not_an_issue", "fixed"],
                        help="Filter by status (repeatable). Default: open")
    args = parser.parse_args()

    if not CHECKLIST_FILE.exists():
        print(f"No checklist found at {CHECKLIST_FILE.relative_to(REPO)}")
        print(f"Run: uv run python tools/bear_cub_generate_checklist.py")
        sys.exit(1)

    data = json.loads(CHECKLIST_FILE.read_text())

    if args.all:
        wanted_statuses = {"open", "not_an_issue", "fixed"}
    elif args.status:
        wanted_statuses = set(args.status)
    else:
        wanted_statuses = {"open"}

    n_holes = 0
    n_items = 0
    for fs in sorted(data.keys()):
        if args.hole and fs != args.hole:
            continue
        items = data[fs].get("items", [])
        filtered = [it for it in items if it.get("status", "open") in wanted_statuses]
        if not filtered:
            continue
        n_holes += 1
        n_items += len(filtered)
        print(f"\n{fs}")
        for it in filtered:
            badge = STATUS_BADGES.get(it.get("status", "open"), it.get("status", ""))
            cat = it.get("category", "")
            desc = it.get("description", "").replace("\n", " ")
            # Truncate long descriptions for the listing
            if len(desc) > 200:
                desc = desc[:197] + "..."
            print(f"  {badge} {it['id']:<32s} ({cat})")
            print(f"                 {desc}")
            comment = (it.get("comment") or "").strip()
            if comment:
                print(f"                 → comment: {comment}")
            resolved = it.get("resolved_at")
            if resolved and it.get("status") in ("not_an_issue", "fixed"):
                print(f"                 → resolved: {resolved}")

    print()
    if args.all:
        label = "items"
    elif args.status:
        label = f"items ({'+'.join(sorted(wanted_statuses))})"
    else:
        label = "open items"
    print(f"Total: {n_holes} holes with {n_items} {label}.")


if __name__ == "__main__":
    main()
